### ISSUE TITLE
Display results as a text would be really helpful

### ISSUE THREAD

**Issue by witoldsz** [le-yams/nbmongo#52] opened 2016-01-23 00:03 UTC
There are two display modes for a collection's data: tree and a flat table. It would be awesome to have third option to see a result set as a JSON text, like:
```
/* 0 */
{
  "_id": "123",
  "somethin": "else"
}

/* 1 */
{
  "_id: "456",
  "another": "..."
}

/* 2 */
{...etc...}
```

It would really help a lot!

**Comment by le-yams** [comment] 2016-01-23 14:00
Hi witoldsz,

That's a nice feature to add, I'll work on this ;-).

Thanks again for all your feedback.

Best regards,
Yann

**Comment by witoldsz** [comment] 2016-01-28 16:44
Works like a charm :)

**Comment by le-yams** [comment] 2016-01-28 17:07
Thank you for the feedback :). I think I'll add a quick search feature like in the document editor.

**Comment by witoldsz** [comment] 2016-01-28 21:54
Hi,
I have discovered but one bug with the editor used to display JSON results. It happens with large documents with arrays so big that they are longer than screen width. In such a case the editor's bottom is below parent's viewport, so the horizontal rule is invisible, the lower part of vertical one is also off the pane.
I would take a picture, but right now I am using other PC. I can prepare a screenshot if you wish, do you?

**Comment by le-yams** [comment] 2016-01-29 00:10
Hi,
I can't reproduce this bug so yes a screenshot would be useful and if you also can pastebin the field text, it would be even better :)

**Comment by le-yams** [comment] 2016-09-26 23:19
I'm closing this issue which was about adding the feature.
@witoldsz  don't hesitate to reopen a new issue for the bug you mentioned with as much details as possible. Thank you :)

Best regards,
Yann

**Closed by le-yams** 2016-09-26 23:19 UTC
Labels: enhancement
